import { Availability, Booking, EventTypeSettings } from "./types";
import { CSSProperties } from "react";
import { DefaultTheme } from "styled-components";
type Props = {
    availability: Partial<Availability>;
    isFetching: boolean;
    eventTypeSetting: EventTypeSettings;
    bookings: Booking[] | undefined;
    onSuccess?: (response: Booking | undefined) => void;
    onError?: (error: unknown) => void;
    bookingToBeRescheduled?: Booking;
    responses?: Record<string, any>;
    duration?: number;
    theme?: DefaultTheme;
    styles?: CSSProperties | undefined;
    LoadingIndicator?: JSX.Element | undefined;
    NoEventError?: JSX.Element | undefined;
    isRoundRobin?: boolean;
    isError?: boolean;
};
export declare const BookingCalendar: ({ availability, isFetching, theme, styles, eventTypeSetting, bookingToBeRescheduled, duration, responses, bookings, LoadingIndicator, NoEventError, isRoundRobin, isError, onError, onSuccess, }: Props) => JSX.Element;
export {};
